name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          base: master
          head: master
          merge_method: rebase
